### ISSUE TITLE
Not working in python 3.3, 3.5, 3.6. Am I missing something

### ISSUE THREAD

**Issue by vaibhav6233m** [rndusr/torf#1]
Does it only works on python 3.6??
I installed torf using 
`pip install torf`

I am just trying out the example provided When I try this on Python 3.6 virtualenv

`import torf

t = torf.Torrent(path='1.jpg',
                 trackers=['https://tracker1.example.org:1234/announce',
                           'https://tracker1.example.org:1234/announce'],
                 comment='This is a comment')
t.private = True`

I get this

`Traceback (most recent call last):
  File "/home/vaibhav/projects/test/py36test/torf.py", line 1, in <module>
    import torf
  File "/home/vaibhav/projects/test/py36test/torf.py", line 3, in <module>
    t = torf.Torrent(path='1.jpg',
AttributeError: module 'torf' has no attribute 'Torrent'`

I am getting this on every python envs.

I tried this on python3.3
`from torf import Torrent`

`Python 3.3.5 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:22:11) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torf import Torrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vaibhav/anaconda3/envs/iag/lib/python3.3/site-packages/torf/__init__.py", line 26, in <module>
    from ._errors import *
  File "/home/vaibhav/anaconda3/envs/iag/lib/python3.3/site-packages/torf/_errors.py", line 37
    super().__init__(f'{url}: Invalid URL')
                                         ^
SyntaxError: invalid syntax
`

Am I missing out something?

**Comment by rndusr** [comment]
Works perfectly fine for me with `pip3 install --user torf` on Debian.

```
Python 3.6.4 (default, Jan  5 2018, 02:13:53) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torf
>>> t = torf.Torrent()
>>> t
Torrent()
>>> 
```

Sorry, I have no idea what could be the issue.

**Comment by vaibhav6233m** [comment]
Does it only works on Python 3.6?

**Comment by rndusr** [comment]
Yes, but that's because it uses f-strings, which should produce a different
error message on lower Python versions.

Besides, your initial report looks like you're using 3.6.

**Comment by vaibhav6233m** [comment]
Okay, I see. But I am still not able to run it on the python 3.6.

**Comment by rndusr** [comment]
I just noticed that the code from the example you posted initially exists in a
file called `torf.py`. AFAIK, python tries to import from the current working
directory first, so it finds a file `torf.py`, which contains the example code,
not the torf module, and therefore no `Torrent` class.

**Comment by vaibhav6233m** [comment]
Ohh I see, thanks for the heads up.

On 09-Feb-2018 7:51 PM, rndusr <notifications@github.com> wrote:
I just noticed that the code from the example you posted initially exists in a
file called `torf.py`. AFAIK, python tries to import from the current working
directory first, so it finds a file `torf.py`, which contains the example code,
not the torf module, and therefore no `Torrent` class.
